Reader reads a set of documents and yield each document.

DirRecursiveReader reads recursively into a directory and yield every file that satisfied a given predicate.

FileFragmentReader is pipelined with any reader as its source, and yield every file fragment generated by given algorithm.
